fixes on Jeninins file ssm deploy fail

diff --git a/ci/jenkins/Jenkinsfile b/ci/jenkins/Jenkinsfile
--- a/ci/jenkins/Jenkinsfile
+++ b/ci/jenkins/Jenkinsfile
@@ -129,8 +129,6 @@ pipeline {
         stage('Deploy via SSM') {
             steps {
                 sh '''
-                 
-                   
                 aws ssm send-command --targets "Key=tag:Role,Values=app" --document-name "AWS-RunShellScript" --parameters commands='[
                    "PREV_IMAGE=$(docker inspect --format='\''{{.Config.Image}}'\'' devops-app 2>/dev/null || echo none)",
                    "echo $PREV_IMAGE > /tmp/prev_image",
@@ -138,34 +136,29 @@ pipeline {
                    "docker stop devops-app || true",
                    "docker rm devops-app || true",
                    "docker run -d --name devops-app -p 80:80 '${ACCOUNT_ID}'.dkr.ecr.'${AWS_REGION}'.amazonaws.com/'${ECR_REPO}':'${GIT_COMMIT_SHORT}'"
-                   ]'        
+                   ]' --output text --query "Command.CommandId" > /tmp/ssm_command_id
                   '''
             }
         }
 
 
-        stage('Verify Health'){
-         steps {
-             sh '''
-             
-             if curl -f --max-time 3 --retry 3 http://${ALB_DNS}/health > /dev/null; then
-               echo "Health OK"
-               exit 0
-             else
-               echo "Health failed"
-               aws ssm send-command --targets "Key=tag:Role,Values=app" --document-name "AWS-RunShellScript" --parameters commands='[
-                 "docker stop devops-app || true",
-                 "docker rm devops-app || true",
-                 "docker run -d --name devops-app -p 80:80 $(cat /tmp/prev_image)"
-               ]'
-               exit 1
-               fi
-     
-               '''
-       
-         }
-         
-    
+         stage('Verify Health') {
+             steps {
+                 sh '''
+                 if curl -f --max-time 3 --retry 3 http://${ALB_DNS}/health > /dev/null; then
+                     echo "Health OK"
+                 else
+                     echo "Health failed - rolling back"
+                     aws ssm send-command --targets "Key=tag:Role,Values=app" --document-name "AWS-RunShellScript" --parameters commands='[
+                         "docker stop devops-app || true",
+                         "docker rm devops-app || true",
+                         "docker run -d --name devops-app -p 80:80 $(cat /tmp/prev_image)"
+                     ]'
+                     exit 1
+                 fi
+             '''
+            }
         }
+    
     }
 }
